#!/usr/bin/env python3
"""
Local task tracker for the Clara AI pipeline.

Creates and updates a tasks.json file per account per pipeline run.
Optional: if GITHUB_TOKEN and GITHUB_REPO env vars are set, also creates GitHub Issues.
"""

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

TASKS_FILE = Path(__file__).parent.parent / "changelog" / "tasks.json"


def _load_tasks() -> dict:
    if TASKS_FILE.exists():
        try:
            with open(TASKS_FILE) as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            logger.warning(f"Could not load tasks from {TASKS_FILE}, starting fresh")
    return {"tasks": [], "last_updated": None}


def _save_tasks(data: dict) -> None:
    TASKS_FILE.parent.mkdir(parents=True, exist_ok=True)
    data["last_updated"] = datetime.now(timezone.utc).isoformat()
    with open(TASKS_FILE, "w") as f:
        json.dump(data, f, indent=2)
    logger.debug(f"Tasks saved to {TASKS_FILE}")


def _find_task(tasks: list, account_id: str, pipeline: str) -> Optional[dict]:
    for task in tasks:
        if task.get("account_id") == account_id and task.get("pipeline") == pipeline:
            return task
    return None


def create_or_update_task(
    account_id: str,
    company_name: str,
    pipeline: str,
    status: str,
    v1_outputs: Optional[list] = None,
    v2_outputs: Optional[list] = None,
    changelog_path: Optional[str] = None,
    notes: Optional[str] = None,
) -> dict:
    """Create or update a tracker entry for an account pipeline run."""
    data = _load_tasks()
    tasks = data["tasks"]
    now = datetime.now(timezone.utc).isoformat()

    existing = _find_task(tasks, account_id, pipeline)
    if existing:
        existing["status"] = status
        existing["updated_at"] = now
        if v1_outputs:
            existing["v1_outputs"] = v1_outputs
        if v2_outputs:
            existing["v2_outputs"] = v2_outputs
        if changelog_path:
            existing["changelog_path"] = changelog_path
        if notes:
            existing["notes"] = (existing.get("notes") or "") + "\n" + notes
        task = existing
        logger.info(f"Updated task for {account_id} ({pipeline}): {status}")
    else:
        task = {
            "task_id": str(uuid.uuid4())[:8],
            "account_id": account_id,
            "company_name": company_name,
            "pipeline": pipeline,
            "status": status,
            "created_at": now,
            "updated_at": now,
            "v1_outputs": v1_outputs or [],
            "v2_outputs": v2_outputs or [],
            "changelog_path": changelog_path,
            "notes": notes or "",
        }
        tasks.append(task)
        logger.info(f"Created task for {account_id} ({pipeline}): {status}")

    _save_tasks(data)

    github_token = os.environ.get("GITHUB_TOKEN")
    github_repo = os.environ.get("GITHUB_REPO")
    if github_token and github_repo and pipeline == "pipeline_a" and status == "completed":
        _create_github_issue(task, github_token, github_repo)

    return task


def _create_github_issue(task: dict, token: str, repo: str) -> None:
    """Create a GitHub Issue for a completed pipeline_a task (optional)."""
    try:
        import urllib.request
        import urllib.error

        title = f"[Clara AI] New Agent Ready: {task['company_name']} ({task['account_id']})"
        body = f"""## New Retell Agent Draft Ready

**Account ID:** {task['account_id']}
**Company:** {task['company_name']}
**Pipeline:** {task['pipeline']}
**Status:** {task['status']}
**Created:** {task['created_at']}

### Outputs
- v1 Memo: {', '.join(task.get('v1_outputs') or [])}
- v2 Memo: {', '.join(task.get('v2_outputs') or [])}
- Changelog: {task.get('changelog_path') or 'N/A'}

### Next Steps
- [ ] Review generated Retell Agent Spec
- [ ] Import spec into Retell UI (see README for manual import instructions)
- [ ] Conduct QA call with client
- [ ] Go live

---
*Auto-generated by Clara AI pipeline*
"""
        payload = json.dumps({"title": title, "body": body, "labels": ["clara-ai", "agent-draft"]})
        url = f"https://api.github.com/repos/{repo}/issues"
        req = urllib.request.Request(
            url,
            data=payload.encode(),
            headers={
                "Authorization": f"token {token}",
                "Content-Type": "application/json",
                "Accept": "application/vnd.github.v3+json",
            },
            method="POST"
        )
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            logger.info(f"GitHub Issue created: {result.get('html_url')}")
    except Exception as e:
        logger.warning(f"GitHub Issue creation failed (non-blocking): {e}")


def list_tasks(filter_status: Optional[str] = None) -> list:
    data = _load_tasks()
    tasks = data["tasks"]
    if filter_status:
        tasks = [t for t in tasks if t.get("status") == filter_status]
    return tasks


def print_summary() -> None:
    data = _load_tasks()
    tasks = data["tasks"]
    if not tasks:
        print("No tasks found.")
        return
    print(f"\n{'='*60}")
    print(f"CLARA AI PIPELINE TASKS ({len(tasks)} total)")
    print(f"{'='*60}")
    for t in tasks:
        print(
            f"  [{t.get('task_id','')}] {t['account_id']} | {t['company_name'][:30]:<30} "
            f"| {t['pipeline']:<12} | {t['status'].upper():<12} | {t['updated_at'][:10]}"
        )
    print(f"{'='*60}\n")


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG, format="%(levelname)s: %(message)s")
    print_summary()
